#!/bin/bash
if [ $# -eq 0 ]
then
	echo "error: need at least 1 arg"
	exit 1
fi

sudo chmod 1777 /trash
flag_f=false
flag_r=false
flag_R=false
trash="/trash"
delInfo="/trash/delInfo"
mode="default"
mkdir -p "$trash"

default_mode(){

	for file in "$@"
	do
		if [ -d "$file" ] && [ "$flag_r" != "true" ]; then
            echo "can't junk dir, use -r instead"
            continue
        fi
		local src_name="$(basename "${file}")"
		local src_path="$(realpath -s "${file}")"
		local target_name="${src_name}"
		local target_path="$trash/${src_name}"
		
        while [ -e "$target_path" ]
		do
			target_name="${src_name}_$(date +%s)"
            target_path="${trash}/${target_name}"
        done

        if mv "$file" "$target_path"
		then
            echo "${target_name}|${src_path}" >> "${delInfo}"
        else
            echo "error: failed to junk: $file"
        fi
	done
}

f_mode(){
	for file in "$@"
	do
		if [ -d "$file" ] && [ "$flag_r" != "true" ]; then
            echo "can't junk dir, use -r instead"
            continue
        fi

		local src_path="$(realpath -s "${file}")"

		if ! rm -rf "${src_path}"
		then
			echo "error: failed to junk: $file"
		fi

	done
}

R_mode(){
	OLD_COLUMNS="${COLUMNS}"
	COLUMNS=1
	for file in "$@"
	do
		local src_name="$(basename "${file}")"
		local target_name="${src_name}"
		local target_path="$trash/${src_name}"

		mapfile -t result < <(
        grep "${target_name}" "$delInfo" | tac )

		if [ ${#result[@]} -eq 0 ]
		then
        	echo "no such file in trash"
        	continue
    	fi

		PS3="请选择要恢复的版本 (输入编号): "
		select item in "${result[@]}" "cancel"; do
			if [[ "$item" == "cancel" ]]
			then
				echo "操作已取消。"
				break
			elif [[ -n "$item" ]]
			then
				IFS='|' read -r target_name ori_path <<< "${item}"
				
				if mv "$trash/$target_name" "$ori_path"
				then
					sed -i "\#${target_name}|${ori_path}#d" "$delInfo"
					echo "成功恢复: $ori_path"
				else
					echo "恢复失败！请检查目标路径是否存在。"
				fi
				break
			else
				echo "无效输入，请重新选择。"
			fi
		done
    done
	COLUMNS=$OLD_COLUMNS
}

while getopts "frR" opt; do
    case $opt in
        f) 
            if [ "$mode" != "default" ]; then
                echo "error: -f, -R, and default mode are mutually exclusive"
                exit 1
            fi
            mode="f" 
            ;;
        r) flag_r=true ;;
        R) 
            if [ "$mode" != "default" ]; then
                echo "error: -f, -R, and default mode are mutually exclusive"
                exit 1
            fi
            mode="R" 
            ;;
        *) 
            echo "unknown option: -$opt"
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

case "$mode" in
    R) R_mode "$@" ;;
    f) f_mode "$@" ;;
    default) default_mode "$@" ;;
esac
	
		
	

